[project]
name = "isyglt"
version = "0.1.0"
description = "Simulates ISYGLT IP-Master Modbus interface"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymodbus>=3.0.0",
    "websockets>=12.0",
]
